# Generated by Django 3.2.18 on 2023-04-26 16:22

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_last_login_on_interactive_user'),
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='WalletID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='WalletUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('bank_name', models.CharField(blank=True, db_column='bank_name', max_length=50, null=True)),
                ('wallet_address', models.CharField(blank=True, db_column='Wallet_address', max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'tblWallet',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='premium',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='WalletMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet', to='core.mutationlog')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='contribution.wallet')),
            ],
            options={
                'db_table': 'WalletMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
