# Generated by Django 3.2.18 on 2023-04-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20201021_0811'),
        ('payer', '0001_initial'),
        ('contribution', '0002_auto_20230426_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='remarks',
            field=models.TextField(blank=True, db_column='remarks', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='wallet_address',
            field=models.ForeignKey(blank=True, db_column='WalletID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='premiums', to='contribution.wallet'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='is_offline',
            field=models.BooleanField(blank=True, db_column='isOffline', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='is_photo_fee',
            field=models.BooleanField(blank=True, db_column='isPhotoFee', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='pay_type',
            field=models.CharField(choices=[('B', 'Bank transfer'), ('C', 'Cash'), ('M', 'Mobile phone'), ('F', 'Funding')], db_column='PayType', max_length=10),
        ),
    ]
