# Generated by Django 3.2.19 on 2023-07-18 11:55

from django.db import migrations, models
from django.db.migrations import RunPython


def add_field_for_psql(apps, schema_editor):
    # Add field only for PostgreSQL
    if schema_editor.connection.vendor == 'postgresql':
        print("FIELDS ADDED CONFIRMED ")
        migrations.AddField(
            model_name='premium',
            name='all_details_commission_report',
            field=models.DateTimeField(blank=True, db_column='AllDetailsCommissionReport', null=True),
        )
        migrations.AddField(
            model_name='premium',
            name='overview_commission_report',
            field=models.DateTimeField(blank=True, db_column='OverviewCommissionReport', null=True),
        )
        migrations.AddField(
            model_name='premium',
            name='reporting_commission_id',
            field=models.IntegerField(blank=True, db_column='ReportingCommissionID', null=True),
        )


def remove_field_for_psql(apps, schema_editor):
    # Remove field only for PostgreSQL
    if schema_editor.connection.vendor == 'postgresql':
        migrations.RemoveField(
            model_name='premium',
            name='all_details_commission_report',
        )
        migrations.RemoveField(
            model_name='premium',
            name='overview_commission_report',
        )
        migrations.RemoveField(
            model_name='premium',
            name='reporting_commission_id',
        )


class Migration(migrations.Migration):
    dependencies = [
        ('contribution', '0003_alter_premium_options'),
    ]

    # For MSSQL This changes were added through raw sql, to keep consistency with existing databases it couldn't be
    # changed in postgres sql script.
    operations = [
        migrations.RunPython(add_field_for_psql, remove_field_for_psql, hints={"target_db": "default"}),
    ]
