# Generated by Django 3.2.19 on 2023-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0003_alter_premium_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='all_details_commission_report',
            field=models.DateTimeField(blank=True, db_column='AllDetailsCommissionReport', null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='overview_commission_report',
            field=models.DateTimeField(blank=True, db_column='OverviewCommissionReport', null=True),
        ),
        migrations.AddField(
            model_name='premium',
            name='reporting_commission_id',
            field=models.IntegerField(blank=True, db_column='ReportingCommissionID', null=True),
        ),
    ]
