# Generated by Django 3.2.21 on 2023-11-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0001_initial'),
        ('contribution', '0003_alter_premium_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, db_column='PaymentTransaction_Id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='premiums', to='mobile_payment.paymenttransaction'),
        ),
    ]
