# Generated by Django 3.2.18 on 2023-05-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20201021_0811'),
        ('payer', '0001_initial'),
        ('contribution', '0004_auto_20230502_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='audit_user_id',
        ),
    ]
