# Generated by Django 3.2.21 on 2023-09-14 12:11

from django.conf import settings
from django.db import migrations, models


class AddFieldPostgres(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_backwards(app_label, schema_editor, from_state, to_state)

    def describe(self):
        # This is used to describe what the operation does in console output.
        return "Wrapper for AddField that works only for postgres database engine."



class Migration(migrations.Migration):
    dependencies = [
        ('contribution', '0005_alter_created_date'),
    ]

    # For MSSQL These changes were added through raw sql, to keep consistency with existing databases it couldn't be
    # changed in postgres sql script.
    operations = []
    if not settings.MSSQL:
        operations = [
            AddFieldPostgres(
                model_name='premium',
                name='source',
                field=models.CharField(db_column="Source", max_length=50, blank=True, null=True),
            ),
            AddFieldPostgres(
                model_name='premium',
                name='source',
                field=models.CharField(db_column="SourceVersion", max_length=15, blank=True, null=True)
            ),
        ]
