# Generated by Django 3.2.18 on 2023-05-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20201021_0811'),
        ('payer', '0001_initial'),
        ('contribution', '0006_auto_20230502_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Merchant_Wallet',
        ),
        migrations.RenameField(
            model_name='premium',
            old_name='wallet_address',
            new_name='wallet',
        ),
       
    ]
