# Generated by Django 3.2.18 on 2023-05-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payer', '0001_initial'),
        ('policy', '0003_auto_20201021_0811'),
        ('contribution', '0007_auto_20230502_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='pay_type',
            field=models.CharField(db_column='PayType', max_length=25),
        ),
    ]
