# Generated by Django 3.2.18 on 2023-05-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0003_insureepolicy'),
        ('policy', '0003_auto_20201021_0811'),
        ('payer', '0001_initial'),
        ('contribution', '0008_auto_20230502_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='Insuree',
            field=models.ForeignKey(blank=True, db_column='InsureeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='premiums', to='insuree.insuree'),
        ),
    ]
