# Generated by Django 3.2.18 on 2023-05-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payer', '0001_initial'),
        ('policy', '0003_auto_20201021_0811'),
        ('contribution', '0010_auto_20230512_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_wallet',
            name='wallet_address',
            field=models.IntegerField(db_column='Wallet_address', default=0, unique=True),
        ),
        
    ]
