# Generated by Django 3.2.18 on 2023-06-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payer', '0001_initial'),
        ('policy', '0003_auto_20201021_0811'),
        ('contribution', '0011_auto_20230512_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='Insuree',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='merchant_wallet',
            name='wallet_address',
            field=models.CharField(db_column='Wallet_address', default=0, max_length=36, unique=True),
        ),
    ]
