# Generated by Django 3.2.18 on 2023-06-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20201021_0811'),
        ('payer', '0001_initial'),
        ('contribution', '0012_auto_20230612_1700'),
    ]

    operations = [
       
    ]
