# Generated by Django 3.2.18 on 2023-07-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payer', '0001_initial'),
        ('policy', '0003_auto_20201021_0811'),
        ('contribution', '0013_auto_20230613_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_wallet',
            name='pin',
            field=models.CharField(db_column='PinNumber', default=False, max_length=128),
        )
    ]
