# Generated by Django 3.2.20 on 2023-08-10 16:10

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20201021_0811'),
        ('payer', '0001_initial'),
        ('contribution', '0014_auto_20230703_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentServiceProvider',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='PSPID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PSPUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('PSPName', models.CharField(blank=True, db_column='PSPName', max_length=50, null=True)),
                ('PSPAccount', models.CharField(db_column='PSPAccount', default=0, max_length=36, unique=True)),
                ('Pin', models.CharField(db_column=' Pin', default=False, max_length=128)),
            ],
            options={
                'db_table': 'tblPaymnet_Service_Provider',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentServiceProviderMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PaymentServiceProviderMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
        migrations.RemoveField(
            model_name='walletmutation',
            name='mutation',
        ),
        migrations.RemoveField(
            model_name='walletmutation',
            name='wallet',
        ),
    ]
