# Generated by Django 3.2.20 on 2023-08-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0001_initial'),
        ('contribution', '0015_auto_20230810_1610'),
        ('core', '0016_add_last_login_on_interactive_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='transaction',
            field=models.ForeignKey(blank=True, db_column='Transaction_Id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='premiums', to='mobile_payment.transactions'),
        ),
        migrations.DeleteModel(
            name='Merchant_Wallet',
        ),
        migrations.DeleteModel(
            name='WalletMutation',
        ),
        migrations.AddField(
            model_name='paymentserviceprovidermutation',
            name='mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_service_provider', to='core.mutationlog'),
        ),
        migrations.AddField(
            model_name='paymentserviceprovidermutation',
            name='payment_service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='contribution.paymentserviceprovider'),
        ),
    ]
