# Generated by Django 3.2.18 on 2023-08-10 16:10

from django.db import migrations


def add_initial_data(contribution, schema_editor):
    PaymentServiceProvider = contribution.get_model('contribution', 'PaymentServiceProvider')
    PaymentServiceProvider.objects.create(PSPName='Qmoney', PSPAccount="14001502", Pin="1234")
    # Add more data as needed

def reverse_add_initial_data(contribution, schema_editor):
    PaymentServiceProvider = contribution.get_model('contribution', 'PaymentServiceProvider')
    PaymentServiceProvider.objects.filter(name='Qmoney').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0016_auto_20230810_1610'),
    ]

    operations = [
        migrations.RunPython(add_initial_data, reverse_code=reverse_add_initial_data),
    ]
