# Generated by Django 3.2.18 on 2023-08-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20201021_0811'),
        ('payer', '0001_initial'),
        ('mobile_payment', '0006_auto_20230829_1433'),
        ('contribution', '0017_auto_20230810_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentserviceprovidermutation',
            name='mutation',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovidermutation',
            name='payment_service_provider',
        ),
        migrations.DeleteModel(
            name='PaymentServiceProvider',
        ),
        migrations.DeleteModel(
            name='PaymentServiceProviderMutation',
        ),
    ]
